/**
 * iCal Export — serves GapNight bookings as a valid .ics feed.
 *
 * URL: GET /api/calendar/:propertyId/:token/calendar.ics
 *
 * The token is a 32-byte hex secret stored on the property row.
 * It is unguessable and can be regenerated by the host at any time.
 * No session cookie is required — this URL is designed to be pasted
 * into Airbnb / Stayz / Booking.com as a calendar import link.
 *
 * The feed includes:
 *   - All CONFIRMED and COMPLETED bookings (check-in → check-out)
 *   - All PENDING_APPROVAL bookings (soft-blocked so host can plan)
 *
 * iCal spec references used:
 *   RFC 5545  — Internet Calendaring and Scheduling Core Object Specification
 *   Airbnb    — uses DATE-only DTSTART/DTEND (not DATETIME)
 *   Stayz     — same as Airbnb
 */

import { Router, Request, Response } from "express";
import { db } from "./db";
import { properties, propertyBookings } from "@shared/schema";
import { eq, and, inArray } from "drizzle-orm";
import crypto from "crypto";

const router = Router();

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Format a YYYY-MM-DD string as an iCal DATE value: YYYYMMDD */
function toICalDate(dateStr: string): string {
  return dateStr.replace(/-/g, "");
}

/**
 * Escape text for iCal property values.
 * RFC 5545 §3.3.11: commas, semicolons, backslashes must be escaped.
 */
function escapeICalText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "");
}

/**
 * Fold long iCal lines at 75 octets (RFC 5545 §3.1).
 * Continuation lines begin with a single space.
 */
function foldLine(line: string): string {
  if (line.length <= 75) return line;
  const chunks: string[] = [];
  // First chunk: 75 chars
  chunks.push(line.slice(0, 75));
  let i = 75;
  while (i < line.length) {
    // Subsequent chunks: 74 chars (1 char used by leading space)
    chunks.push(" " + line.slice(i, i + 74));
    i += 74;
  }
  return chunks.join("\r\n");
}

/** Generate a stable UID for a booking event */
function bookingUid(bookingId: string, propertyId: string): string {
  return `${bookingId}@${propertyId}.gapnight.com.au`;
}

/** Format a JS Date as iCal DTSTAMP (UTC): YYYYMMDDTHHMMSSZ */
function toICalStamp(date: Date): string {
  return date.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, "");
}

// ── Export endpoint ───────────────────────────────────────────────────────────

router.get(
  "/api/calendar/:propertyId/:token/calendar.ics",
  async (req: Request, res: Response) => {
    const propertyId = req.params.propertyId as string;
    const token = req.params.token as string;

    // Basic input validation — tokens are 64-char hex strings
    if (!propertyId || !token || !/^[0-9a-f]{64}$/i.test(token)) {
      return res.status(404).send("Not found");
    }

    try {
      // 1. Look up the property
      const [property] = await db
        .select()
        .from(properties)
        .where(eq(properties.id, String(propertyId)))
        .limit(1);

      if (!property) {
        return res.status(404).send("Not found");
      }

      // 2. Constant-time token comparison to prevent timing attacks
      if (!property.icalExportToken) {
        return res.status(404).send("Not found");
      }

      const expected = Buffer.from(String(property.icalExportToken), "utf8");
      const provided = Buffer.from(token, "utf8");

      // Pad to same length before comparing (timingSafeEqual requires equal lengths)
      const maxLen = Math.max(expected.length, provided.length);
      const a = Buffer.alloc(maxLen);
      const b = Buffer.alloc(maxLen);
      expected.copy(a);
      provided.copy(b);

      if (!crypto.timingSafeEqual(a, b)) {
        return res.status(404).send("Not found");
      }

      // 3. Fetch all bookings that should appear in the feed
      const bookings = await db
        .select()
        .from(propertyBookings)
        .where(
          and(
            eq(propertyBookings.propertyId, String(propertyId)),
            inArray(propertyBookings.status, [
              "PENDING_APPROVAL",
              "APPROVED",
              "CONFIRMED",
              "COMPLETED",
            ])
          )
        );

      // 4. Build the iCal feed
      const now = new Date();
      const stampStr = toICalStamp(now);
      const propertyName = escapeICalText(property.title);
      const lines: string[] = [];

      // Calendar header
      lines.push("BEGIN:VCALENDAR");
      lines.push("VERSION:2.0");
      lines.push("PRODID:-//GapNight//GapNight Calendar//EN");
      lines.push("CALSCALE:GREGORIAN");
      lines.push("METHOD:PUBLISH");
      lines.push(foldLine(`X-WR-CALNAME:GapNight - ${propertyName}`));
      lines.push("X-WR-TIMEZONE:Australia/Sydney");
      lines.push("X-WR-CALDESC:Bookings exported from GapNight");

      for (const booking of bookings) {
        // DTEND in iCal for all-day events is exclusive (the day AFTER checkout)
        // This is correct per RFC 5545 and matches Airbnb's behaviour.
        const dtstart = toICalDate(booking.checkInDate);
        const dtend = toICalDate(booking.checkOutDate);

        // Human-readable summary — don't expose guest PII to other platforms
        const summary =
          booking.status === "PENDING_APPROVAL"
            ? "GapNight - Pending booking"
            : "GapNight - Reserved";

        const uid = bookingUid(booking.id, propertyId);

        // DTSTAMP: when this event was last modified (use booking updatedAt)
        const dtstamp = toICalStamp(
          booking.updatedAt instanceof Date
            ? booking.updatedAt
            : new Date(booking.updatedAt)
        );

        lines.push("BEGIN:VEVENT");
        lines.push(foldLine(`UID:${uid}`));
        lines.push(`DTSTAMP:${dtstamp}`);
        lines.push(`DTSTART;VALUE=DATE:${dtstart}`);
        lines.push(`DTEND;VALUE=DATE:${dtend}`);
        lines.push(foldLine(`SUMMARY:${escapeICalText(summary)}`));
        lines.push("TRANSP:OPAQUE");
        lines.push("STATUS:CONFIRMED");
        lines.push("END:VEVENT");
      }

      lines.push("END:VCALENDAR");

      // iCal uses CRLF line endings (RFC 5545 §3.1)
      const body = lines.join("\r\n") + "\r\n";

      res.setHeader("Content-Type", "text/calendar; charset=utf-8");
      res.setHeader(
        "Content-Disposition",
        `attachment; filename="gapnight-${propertyId}.ics"`
      );
      res.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
      res.setHeader("Pragma", "no-cache");
      res.setHeader("Expires", "0");
      res.status(200).send(body);
    } catch (err) {
      console.error("[iCal Export] Error:", err);
      res.status(500).send("Internal server error");
    }
  }
);

export default router;
